version: 2
jobs:
  build:
    working_directory: ~/anime-music
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
        environment:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:password@localhost:5432/anime-music_test
          DB_PASS: password
          DB_USER: postgres
          DB_HOST: localhost
          REDIS_HOST: redis
      - image: postgres:9.4.12-alpine
        environment:
          POSTGRES_PASSWORD: ""
          POSTGRES_DB: anime-music_test
      - image: redis:4.0.1-alpine
    steps:
      - checkout

      # Install fonts-magmix
      - run: sudo apt-get install fonts-migmix

      # Restore bundle cache
      - type: cache-restore
        key: anime-music-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: gem update bundler
      - run: bundle install --path vendor/bundle

      # Store bundle cache
      - type: cache-save
        key: anime-music-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      # Upgrade npm
      - run: npm install npm@5.4.2

      # Restore npm cache
      - restore_cache:
          name: Restore npm cache
          keys:
            - npm-5.4.2-{{ checksum "package.json" }}

      - run:
          name: Run npm install
          command: npm install

      - save_cache:
          name: Store npm cache
          key: npm-5.4.2-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load

      # Run stylelint
      - run: npm run stylelint app/assets/stylesheets/*

      # Run ESLint
      - run: npm run eslint app/assets/javascripts/**/*.js

      # Run rubocop
      - run: bundle exec rubocop app/ lib/ spec/

      # Run rspec in parallel
      - type: shell
        command: |
          bundle exec rspec \
            --format RspecJunitFormatter \
            --out /tmp/test-results/rspec.xml \
            --format progress \
            $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

      # Export Report of test coverage
      - run: ruby ./bin/coverage_report.rb

      # Export Report of brakeman
      - run: ruby ./bin/brakeman.rb

      # Save artifacts
      - store_artifacts:
          path: ./tmp/capybara
          destination: capybara-screenshot

      - store_artifacts:
          path: ./coverage
          destination: coverage

      - store_artifacts:
          path: ./brakeman
          destination: brakeman

      - store_test_results:
          path: /tmp/test-results
