defaults: &defaults
  site:
    site: アニソンタイム
    title: アニメソング情報サイト
    description: アニソンタイムは、放送中のアニメのオープニングテーマやエンディングテーマの詳細な情報を確認できるサイトです。
    keywords: アニメ,アニソン,アニソン情報,データベース,音楽,歌,歌手,曲,名曲,神曲,オープニング,エンディング,anison,anime,anisontime,アニソンタイム,アニソン★タイム
    og:
      type: website
      locale: ja_JP
  site_image_path: '' # TODO: 画像を設定する
  access_token:
    length: 32
    expire_after: <%= 90.days.to_i %>
  anime:
    summary:
      maximum_length: 50000
    title:
      maximum_length: 250
    wiki_url:
      maximum_length: 50000
  season:
    name:
      maximum_length: 250
  user:
    email:
      maximum_length: 250
    password:
      maximum_length: 250

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
